// diseaseDB_allerji — Dr. Feridun Karadağ Tanı Sistemi (v2.1 Zenginleştirilmiş)
var diseaseDB_allerji={"metadata":{"version":"2.1","total_diseases":6,"language":"Turkish","lastUpdated":"2026-04-09"},"diseases":[
{"id":"Z99.9","name":"ANAFİLAKSİ","englishName":"","category":"Allerji","subcategory":"","prevalence":"medium","gender":"both","ageRange":{"min":0,"max":120},"symptoms":[],"signs":[],"labFindings":["Bulgular Yenidoğan/Bebek Nadirdir","maternal IgE USG: (gastrointestinal Tryptaz: Serum tryptaz plasentadan geçmez"],"pathology":[],"radiology":[],"course":"","complications":[],"treatment":[]},
{"id":"Z99.9","name":"IgE-Aracılı Yiyecek Allerjisi","englishName":"","category":"Allerji","subcategory":"","prevalence":"medium","gender":"kadın","ageRange":{"min":0,"max":120},"symptoms":[],"signs":[],"labFindings":["Bulgular Çocuk (Süt","Akut başlangıç (dakikalar-2 Endoskopi: (EoE şüphesinde) Spesifik IgE (sIgE): (serum","yumurta","fıstık","saat): ürtiker","anjiyoödem","özofageal ImmunoCAP) >0.35 kU/L pozitif","ceviz","buğday","soya en pruritus","oral allergy syndrome eosinofili","USG: (gastrointestinal klinik korelasyon gerekli; Skin sık) (oral pruritus"],"pathology":[],"radiology":[],"course":"","complications":[],"treatment":[]},
{"id":"Z99.9","name":"Non-IgE Aracılı Yiyecek Allerjisi","englishName":"","category":"Allerji","subcategory":"","prevalence":"medium","gender":"both","ageRange":{"min":0,"max":120},"symptoms":[],"signs":[],"labFindings":["Bulgular Yenidoğan/Bebek FPIES (Food Protein-Induced USG: (FPIES'de) kolonik duvar CBC: (FPIES'de) nötrofili","Enterocolitis kalınlaşması","Endoskopi: (FPIAP/FPIE'de) trombositoz","Metabolik: (FPIES'de) metabolik Syndrome): Tekrarlayan şiddetli lenfoid nodüler hiperplazi","villus atrofi asidoz","Stool: (FPIAP'de) kan","mükus","nötrofiller","kusma (2-4 saat sonra","letarji","(FPIE) eosinofiller (değişken"],"pathology":[],"radiology":[],"course":"","complications":[],"treatment":[]},
{"id":"Z99.9","name":"Allerjik Rinit","englishName":"","category":"Allerji","subcategory":"","prevalence":"medium","gender":"both","ageRange":{"min":0,"max":120},"symptoms":[],"signs":[],"labFindings":["Bulgular Çocuk"],"pathology":[],"radiology":[],"course":"","complications":[],"treatment":[]},
{"id":"Z99.9","name":"Allerjik Astım","englishName":"","category":"Allerji","subcategory":"","prevalence":"medium","gender":"both","ageRange":{"min":0,"max":120},"symptoms":[],"signs":[],"labFindings":["Bulgular Çocuk (5"],"pathology":[],"radiology":[],"course":"","complications":[],"treatment":[]},
{"id":"Z99.9","name":"İLAÇ ALLERJİSİ ve HİPERSENSİTİVİTE REAKSİYONLARI","englishName":"","category":"Allerji","subcategory":"","prevalence":"medium","gender":"both","ageRange":{"min":0,"max":120},"symptoms":[],"signs":[],"labFindings":["Bulgular Çocuk Gell-Coombs CXR: (pulmoner infiltratlar - Spesifik IgE: (penisilin Sınıflaması: (1) Tip I DRESS","SJS/TEN'de benzylpenicilloyl polylysine (PPL","minor (IgE-aracılı - anafilaksi","pnömoni","HRCT: (interstisyel determinant mix (MDM","amoxicillin","ürtiker","anjiyoödem","pnömoni","organizan ampicillin","cefalosporinler - %10-20 çapraz bronkospazm","(2) Tip II pnömoni"],"pathology":[],"radiology":[],"course":"","complications":[],"treatment":[]}
]};
// Tarayıcı global kaydı (window lookup için)
if (typeof window !== "undefined") window["diseaseDB_allerji"] = diseaseDB_allerji;
