// diseaseDB_geriatri — Dr. Feridun Karadağ Tanı Sistemi (v2.1 Zenginleştirilmiş)
const diseaseDB_geriatri={"metadata":{"version":"2.1","total_diseases":7,"language":"Turkish","lastUpdated":"2026-04-09"},"diseases":[
{"id":"Z99.9","name":"GERİATRİK SENDROM ve DEGERLENDİRMELER","englishName":"","category":"Geriatri","subcategory":"","prevalence":"medium","gender":"both","ageRange":{"min":0,"max":120},"symptoms":[],"signs":[],"labFindings":["Bulgular Erişkin 65-74 Yürüme hızında DEXA: (Appendiküler kas kütlesi EWGSOP2 2018 Kriterleri: (1) yaş azalma","merdiven ölçümü - alt Kas kütlesi düşüklüğü (Young-Old) çıkmada güçlük","ekstremite","BIA: (Bioelektrik (DXA/BIA/CT/MR","(2) Kas gücü sandalyeden impedans analizi - kas düşüklüğü (el kavrama gücü <27 kg kalkmada zorlanma","kütlesi","CT/MR: (L3 seviyesinde erkek, <16 kg kadın","(3) Fiziksel"],"pathology":[],"radiology":[],"course":"","complications":[],"treatment":[]},
{"id":"Z99.9","name":"Frailite","englishName":"","category":"Geriatri","subcategory":"","prevalence":"medium","gender":"both","ageRange":{"min":0,"max":120},"symptoms":[],"signs":[],"labFindings":["CRP yüksek","yılda istemsiz kilo kaybı >5% ölçümü","CT: Visseral albumin düşük (<3.5 g/dL","prealbümin veya 10 lb","(2) Yorgunluk: yağ/SMI düşük","total kolesterol düşük (<160 CES-D ölçeği ile kendini yorgun oranı","USG: Karaciğer mg/dL"],"pathology":[],"radiology":[],"course":"","complications":[],"treatment":[]},
{"id":"G30.9","name":"Alzheimer Hastalığı ve Demanslar","englishName":"","category":"Geriatri","subcategory":"","prevalence":"medium","gender":"kadın","ageRange":{"min":0,"max":120},"symptoms":["İlerleyici hafıza kaybı","kognitif fonksiyon bozukluğu","günlük aktivite bozukluğu","davranış değişiklikleri"],"signs":[],"labFindings":["düşük (<500 pg/mL","total tau yüksek (>300 Bilişsel/kdavranışsal posterior cingulate","precuneus atrofisi","pg/mL","p-tau181 yüksek (>61 pg/mL","Aβ42/40","p-tau217)↑","total tau↑","Nörofilament hafif zincir↑"],"pathology":[],"radiology":["incelme","Amyloid PET: Pozitif tutulum"],"course":"","complications":[],"treatment":[]},
{"id":"G20","name":"Parkinson Hastalığı ve Parkinsonizm","englishName":"","category":"Geriatri","subcategory":"","prevalence":"medium","gender":"kadın","ageRange":{"min":0,"max":120},"symptoms":["Tremor istirahatte","bradikinezi","kas rigiditesi","postural instabilite","mikrografi","hipomimi"],"signs":[],"labFindings":["Bulgular Erişkin 60-70 MDS 2015 MR Beyin: (diferansiyel tanı için) Serum: Normal (spesifik biyomarker yaş Kriterleri: (1) Normal veya minimal atrofi","DATSCAN yok","CSF: Alfa-sinüklein düşük (yayılım (Early-onset) Bradykinezi (zorunlu","(Ioflupane I-123 SPECT): (Dopamin göstergesi","total tau","p-tau","Aβ42 (demans (2) En az bir: rijidite transporter) striatal tutulum azalması overlap","Genetik: LRR","(Simoa paneli","serum NF-L normal veya hafif yüksek"],"pathology":[],"radiology":["birikimi","DAT-SPECT: Striatal dopamin taşıyıcı azalması"],"course":"","complications":[],"treatment":[]},
{"id":"I50.9","name":"Kalp Yetmezliği (Heart Failure with Preserved Ejection Fraction","englishName":"","category":"Geriatri","subcategory":"","prevalence":"medium","gender":"both","ageRange":{"min":0,"max":120},"symptoms":[],"signs":[],"labFindings":["Bulgular Grubu Erişkin HFA-PEFF 2020 Kriterleri: (1) Ekokardiyografi: (Altın BNP: >400 pg/mL (HFpEF için","NT-proBNP: >900 pg/mL (65-74 yaş), >1800 65-74 yaş"],"pathology":[],"radiology":[],"course":"","complications":[],"treatment":[]},
{"id":"S00-T98","name":"Osteoporoz ve Düşme-Kırık Sendromu","englishName":"","category":"Geriatri","subcategory":"","prevalence":"medium","gender":"both","ageRange":{"min":0,"max":120},"symptoms":[],"signs":[],"labFindings":["(Postmenopozal kırık - vertebral","kriteri","Z-skoru (yaşa urine","N-telopeptide (NTX","tartrate-resistant acid kadınlar","önkol","göre","L1-L4 ve femur boyun phosphatase 5b (TRAcP-5b","Formasyon:"],"pathology":[],"radiology":[],"course":"","complications":[],"treatment":[]},
{"id":"N18.9","name":"Kronik Böbrek Hastalığı (CKD) - Geriatrik Özellikler","englishName":"","category":"Geriatri","subcategory":"","prevalence":"medium","gender":"both","ageRange":{"min":0,"max":120},"symptoms":[],"signs":[],"labFindings":["Bulgular Grubu Erişkin KDIGO 2024: eGFR <60 Renal USG: Böbrek boyutu (küçük - eGFR: (CKD-EPI 2021 race-free equation - 65+ yaş için","Cystatin C: (Yaş ve 65-74 yaş mL/min/1.73m² (>3 ay) ve/veya <9 cm","kortikal incelme <1 cm","kas kütlesinden etkilenmez","eGFR hesaplamasında kullanılabilir","Albumin/kreatinin albuminüri (ACR ≥30 artmış ekojenite","Doppler: Renal oranı (ACR): (ACR ≥30 mg/g - albuminü"],"pathology":[],"radiology":[],"course":"","complications":[],"treatment":[]}
]};